language: python
services: postgresql

python:
  - 3.7
node_js:
  - "10.9.0"
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database choban;' -U postgres

script:
- npm run dev
- python manage.py collectstatic --noinput
- python manage.py test