version: '3'

services:
  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: "!9ty9I6oiU@9*b"
        POSTGRES_DB: choban
        POSTGRES_USER: choban
#   redis:
#     image: redis:5.0.3-alpine
#     expose:
#       - 6379
  web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      ports:
        - "8000:8000"
      volumes:
        - ./.env:/backend/.env
        - ./:/backend
