# Generated by Django 2.0.6 on 2018-06-09 11:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('package_uninstall_args', django.contrib.postgres.fields.jsonb.JSONField()),
                ('server', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
