# Generated by Django 2.0.6 on 2018-06-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_args',
            new_name='packageArgs',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='package_uninstall_args',
            new_name='packageUninstallArgs',
        ),
    ]
