# Generated by Django 2.0.6 on 2018-06-10 10:44

import api.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180609_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.FileField(upload_to='', validators=[api.validators.validate_file_extension])),
            ],
        ),
        migrations.CreateModel(
            name='WaitingForApprovalPackages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageName', models.CharField(max_length=100)),
                ('packageArgs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('packageUninstallArgs', django.contrib.postgres.fields.jsonb.JSONField()),
                ('server', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
