# Generated by Django 2.0.6 on 2018-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180620_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
